# np.zeros(), np.ones(), np.random() und np.full()

Es gibt einige Funktionen um mehrdimensionale Arrays zu erstellen:

In [2]:
import numpy as np

### 1. `numpy.zeros()`:

Erstellt ein Array, das nur Nullen enthält, mit der gewünschten Dimension.

In [3]:
arr_3d = np.zeros((2, 3, 4))  # Erstellt ein 2x3x4 Array voll mit Nullen
print(arr_3d)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


### 2. `numpy.ones()`:

Erstellt ein Array, das nur Einsen enthält, mit der gewünschten Dimension.

In [5]:
arr_3d = np.ones((2, 3, 4))  # Erstellt ein 2x3x4 Array voll mit Einsen
print(arr_3d)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


### 3. `numpy.random.rand()`:

Erstellt ein Array mit zufälligen Werten im Bereich von 0 bis 1.

In [7]:
arr_random = np.random.rand(3, 2)  # 3x2 Array mit zufälligen Werten
print(arr_random)

[[0.02897012 0.22335341]
 [0.53736396 0.75287226]
 [0.775809   0.09572524]]


### 5. `numpy.full()`:

Erstellt ein Array, das mit einem festen Wert gefüllt ist.

In [8]:
arr_full = np.full((2, 3), 7)  # 2x3 Array gefüllt mit 7
print(arr_full)

[[7 7 7]
 [7 7 7]]


### Fazit:

- Mit `numpy.array()` kannst du explizit ein mehrdimensionales Array aus Listen erstellen.
- Mit Funktionen wie `zeros()`, `ones()`, `full()`, und `random.rand()` kannst du mehrdimensionale Arrays mit vordefinierten Werten oder zufälligen Werten erzeugen.