Siehe auch: [arr.reshape()](arr.reshape.ipynb)

Siehe auch [Arrays](../Module/Numpy/Arrays.ipynb)

# arange()-Funktion

### Übersicht

`np.arange()` ist eine Funktion in NumPy, die ein Array mit gleichmäßig verteilten Werten innerhalb eines bestimmten Bereichs erstellt. Es funktioniert ähnlich wie die Python `range()`-Funktion, aber für Arrays und mit zusätzlicher Flexibilität bei Schrittweiten.

### Syntax: 

`arange` `(` `start` `,` `stop` `,` `step` `,` `dtype` `)`

```python
arange([start,] stop[, step], [, dtype=None])
```

### Zusammenfassung


- Bis auf `stop` ist alles optional.
- Die Default Werte der arange Funktion sind:
```python
start = 0
step = 1
dtype=None
```
- **np.arange(stop):** Erzeugt Werte von `0` bis `stop` (exklusiv).
- **np.arange(start, stop):** Erzeugt Werte von `start` bis `stop` (exklusiv).
- **np.arange(start, stop, step):** Erzeugt Werte von `start` bis `stop` (exklusiv) mit der Schrittweite `step`.
- Default return: Array
- Error: ?

## Beispiele:

### Beispiel 1: Ganzzahlen

In [7]:
# Erzeugt ein Array von 0 bis 9 (Schritte von 1)
import numpy as np

array_1 = np.arange(10)
print(array_1)

[0 1 2 3 4 5 6 7 8 9]


### Beispiel 2: Start, Stopp und Schrittweite

In [9]:
import numpy as np

# Erzeugt ein Array von 5 bis 15 (exklusiv) in Schritten von 2
array_2 = np.arange(5, 15, 2)
print(array_2)

[ 5  7  9 11 13]


### Beispiel 3: Gleitkommazahlen

In [10]:
import numpy as np

# Erzeugt ein Array von 0 bis 1 in Schritten von 0.2
array_3 = np.arange(0, 1, 0.2)
print(array_3)

[0.  0.2 0.4 0.6 0.8]


# Mehrdeminsionale Arrays

In [1]:
import numpy as np

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)


[[1 2 3]
 [4 5 6]]
