# np.meshgrid()

Die Funktion `np.meshgrid()` von NumPy erzeugt aus zwei eindimensionalen Arrays zwei zweidimensionale Matrizen, die als Koordinatensysteme dienen. Sie wird oft in der Visualisierung und in numerischen Berechnungen verwendet, um Gitterpunkte in einem 2D- oder 3D-Raum zu erzeugen.

### Funktionsweise
Angenommen, wir haben zwei Arrays:
- `x = [1, 2, 3]` (die x-Koordinaten)
- `y = [4, 5]` (die y-Koordinaten)

`np.meshgrid(x, y)` erzeugt zwei Arrays:
- Ein Array für die x-Koordinaten, das die Werte von `x` für jede Zeile wiederholt.
- Ein Array für die y-Koordinaten, das die Werte von `y` für jede Spalte wiederholt.

### Beispiel in Python

In [1]:
import numpy as np

# Koordinaten-Arrays
x = [1, 2, 3]
y = [4, 5]

# Meshgrid erzeugen
X, Y = np.meshgrid(x, y)

print("X-Koordinaten:")
print(X)

print("\nY-Koordinaten:")
print(Y)

X-Koordinaten:
[[1 2 3]
 [1 2 3]]

Y-Koordinaten:
[[4 4 4]
 [5 5 5]]


### Erklärung des Ergebnisses
- Das `X`-Array enthält die Werte `[1, 2, 3]` für jede Zeile, was die x-Koordinaten für jede y-Position darstellt.
- Das `Y`-Array enthält die Werte `[4, 5]` für jede Spalte, was die y-Koordinaten für jede x-Position darstellt.

Das `meshgrid` wird oft in Kombination mit Funktionen wie `matplotlib` verwendet, um 3D-Plots zu erzeugen oder Flächen zu visualisieren.