# np.ravel()

`np.ravel()` ist eine Funktion aus der `NumPy`-Bibliothek, die ein mehrdimensionales Array in ein eindimensionales Array (1D) umwandelt. Im Gegensatz zu `flatten()` versucht `ravel()` jedoch, eine Ansicht des Originalarrays zurückzugeben, wenn möglich, anstatt eine Kopie zu erzeugen. Das bedeutet, dass Änderungen an dem von `ravel()` erzeugten Array manchmal auch das Originalarray beeinflussen können.

### Kurz zusammengefasst
- **`np.ravel()`** macht aus einem mehrdimensionalen Array ein eindimensionales Array.
- Gibt, wenn möglich, eine Ansicht auf die Originaldaten zurück (ist effizienter als `flatten()`).
- Änderungen im Ergebnisarray können das Originalarray beeinflussen, falls eine Ansicht zurückgegeben wurde.

### Beispiel

```python
import numpy as np

# Ein 2D-Array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Mit np.ravel() in ein 1D-Array umwandeln
array_1d = np.ravel(array_2d)

print("Original Array:")
print(array_2d)
print("Geraveltes Array:")
print(array_1d)
```

**Ausgabe:**
```
Original Array:
[[1 2 3]
 [4 5 6]]
Geraveltes Array:
[1 2 3 4 5 6]
```

Falls `ravel()` eine Ansicht zurückgibt, und du danach das Ergebnis veränderst, könnte das Originalarray ebenfalls beeinflusst werden:

```python
array_1d[0] = 99
print("Modifiziertes geraveltes Array:", array_1d)
print("Modifiziertes Original Array:", array_2d)
```

**Ausgabe:**
```
Modifiziertes geraveltes Array: [99 2 3 4 5 6]
Modifiziertes Original Array:
[[99  2  3]
 [ 4  5  6]]
```

### Wann `np.ravel()` zu verwenden ist
- Wenn du ein Array nur temporär als 1D-Daten benötigst und die Performance optimieren willst.
- Wenn es dir nichts ausmacht, dass Änderungen an dem geravelten Array das Originalarray beeinflussen könnten.