Siehe auch: [np.arrange()](np.arange.ipynb)

# arr.reshape()

Die Funktion `arange` aus NumPy erstellt ein **eindimensionales** Array, aber sie kann in Kombination mit anderen Funktionen verwendet werden, um ein **mehrdimensionales** Array zu erzeugen.

Hier sind die Schritte, wie das funktioniert:

1. **arange() erzeugt eine Folge von Zahlen**:
   - `arange` erstellt eine 1D-Sequenz von gleichmäßig verteilten Zahlen, ähnlich wie `range()` in Python.

2. **Umwandlung in ein mehrdimensionales Array mit reshape()**:
   - Um diese Folge von Zahlen in ein mehrdimensionales Array zu verwandeln, kann die Methode `reshape()` verwendet werden, um das eindimensionale Array in eine gewünschte Form zu bringen.

### Beispiel:

```python
import numpy as np

# Ein 1D-Array mit Werten von 0 bis 11 (12 Werte)
arr = np.arange(12)

# In ein 3x4 Array umformen (mehrdimensional)
arr_2d = arr.reshape(3, 4)

print(arr_2d)
```

### Erklärung:
- `np.arange(12)` erzeugt das eindimensionale Array: `[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]`.
- `reshape(3, 4)` formt es in ein **3x4**-Array um:
  ```
  [[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]]
  ```

### Mehrdimensionale Arrays (z.B. 3D-Array):

```python
# In ein 2x3x2-Array umformen
arr_3d = arr.reshape(2, 3, 2)
print(arr_3d)
```

Ergebnis:
```
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
```

So kann die Kombination von `arange` und `reshape` verwendet werden, um **mehrdimensionale Arrays** zu erzeugen.