# Matrix und Tensor

**Matrix** (plural Matrizen) und **Tensor** (plural Tensoren) ist fast das gleiche. Ein Tensor ist eine generalisierte Form einer Matrix. Sie sind beide grundlegende Konzepte in der Mathematik und werden in vielen Bereichen der Datenwissenschaft, einschließlich des maschinellen Lernens und der numerischen Berechnung verwendet. 

## Matrix (plural Matrizen)

- **Definition**: Eine Matrix ist ein rechteckiges Array von Zahlen, Symbolen oder Ausdrücken, die in Zeilen und Spalten angeordnet sind. Eine Matrix hat die Dimensionen $m \times n$, wobei $m$ die Anzahl der Zeilen und $n$ die Anzahl der Spalten ist.

- **Notation**: Eine Matrix wird oft mit Großbuchstaben dargestellt, z. B. $A$. Ein Element der Matrix an der Position $i$ (Zeile) und $j$ (Spalte) wird oft als $A_{ij}$ bezeichnet.

- **Anwendungen**:
  - Matrizen werden häufig in der linearen Algebra verwendet, um Systeme von linearen Gleichungen zu lösen.
  - Sie sind auch wichtig in der Computergrafik, um Transformationen durchzuführen (z. B. Skalierung, Rotation).

#### **Beispiel**:

  Eine Matrix $A$ mit 2 Zeilen und 3 Spalten könnte so aussehen:

  $$
  A = \begin{pmatrix}
  1 & 2 & 3 \\
  4 & 5 & 6
  \end{pmatrix}
  $$

### Beispiel: Matrizen mit NumPy

In [16]:
import numpy as np

Wir erstellen eine 2D-Matrix mit `np.array()`.

In [17]:
# Erstelle eine 2D-Matrix (3x3)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [18]:
# Ausgabe der Matrix 
print("2D-Matrix:")
print(matrix)

2D-Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Die Matrix wird transponiert, was bedeutet, dass ihre Zeilen und Spalten vertauscht werden.

In [19]:
# Durchführung von Operationen auf der Matrix
# Transponiere die Matrix
transposed_matrix = np.transpose(matrix)
print("Transponierte Matrix:")
print(transposed_matrix)

Transponierte Matrix:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


Wir berechnen die Summe der Spalten der Matrix mit `np.sum(matrix, axis=0)`.

In [20]:
# Berechnung der Summe entlang einer Achse
sum_over_columns = np.sum(matrix, axis=0)  # Summe der Spalten
print("Summe über Spalten:")
print(sum_over_columns)

Summe über Spalten:
[12 15 18]


## Tensor (plural Tensoren)

- **Definition**: Ein Tensor ist eine generalisierte Form von Matrizen. Tensors können als mehrdimensionale Arrays von Zahlen angesehen werden. Ein Tensor ist also eine Matrix mit einer beliebigen Anzahl von Dimensionen.

- **Dimensionen**:
  - Ein **Skalar** ist ein Tensor 0. Ordnung (z. B. eine einzelne Zahl).
  - Ein **Vektor** ist ein Tensor 1. Ordnung (z. B. eine Liste von Zahlen).
  - Eine **Matrix** ist ein Tensor 2. Ordnung.
  - Tensors höherer Ordnung haben 3 oder mehr Dimensionen (z. B. ein Tensor 3. Ordnung könnte in Form eines Würfels dargestellt werden).

- **Anwendungen**:
  - Tensors sind in vielen Bereichen der Physik, Informatik und Ingenieurwissenschaften nützlich. In der maschinellen Lern-Community werden sie häufig in Frameworks wie TensorFlow und PyTorch verwendet.
  - Sie werden verwendet, um komplexe Datenstrukturen darzustellen, wie z. B. Bilddaten (z. B. ein 3D-Tensor für RGB-Bilder).

- **Beispiel**:

  Ein Tensor 3. Ordnung könnte so aussehen:

  $$
  T = \begin{pmatrix}
  \begin{pmatrix}
  1 & 2 \\
  3 & 4
  \end{pmatrix},
  \begin{pmatrix}
  5 & 6 \\
  7 & 8
  \end{pmatrix}
  \end{pmatrix}
  $$

  Hier stellt jeder Block eine Matrix dar.

### Zusammenfassung

- **Matrizen** sind spezielle Fälle von Tensors, die genau zwei Dimensionen haben. 
- **Tensors** sind flexibler und können beliebig viele Dimensionen haben, wodurch sie eine mächtige Struktur für die Datenanalyse und das maschinelle Lernen bieten.

### Beispiel: Tensor mit NumPy

Ein 3D-Tensor wird ebenfalls mit `np.array()` erstellt.

In [21]:
# Erstelle einen 3D-Tensor (2x3x3)
tensor = np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],
                   
                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]]])

# Ausgabe des Tensors
print("\n3D-Tensor:")
print(tensor)


3D-Tensor:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


Der Tensor wird entlang der ersten Achse transponiert, was bedeutet, dass die ersten beiden Dimensionen vertauscht werden.

In [22]:
# Durchführung von Operationen auf dem Tensor
# Transponiere den Tensor entlang der ersten Achse
transposed_tensor = np.transpose(tensor, (1, 0, 2))
print("\nTransponierter Tensor:")
print(transposed_tensor)


Transponierter Tensor:
[[[ 1  2  3]
  [10 11 12]]

 [[ 4  5  6]
  [13 14 15]]

 [[ 7  8  9]
  [16 17 18]]]


Wir berechnen die Summe über die erste Dimension des Tensors mit `np.sum(tensor, axis=0)`.

In [23]:
# Berechnung der Summe entlang der ersten Achse des Tensors
sum_tensor = np.sum(tensor, axis=0)  # Summe über die erste Dimension
print("\nSumme über die erste Dimension des Tensors:")
print(sum_tensor)


Summe über die erste Dimension des Tensors:
[[11 13 15]
 [17 19 21]
 [23 25 27]]
